name: Build Next.js Project

on:
  push:
    branches:
      - main  # Trigger on push to main (adjust for other branches as needed)
  pull_request:
    branches:
      - main  # Trigger on pull requests targeting main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Specify your Node.js version

    - name: Install dependencies
      run: npm install

    - name: Run build
      run: npm run build

    - name: Run Next.js in production mode (optional)
      run: npm run start  # This step runs the app in production mode
